import Head from 'next/head';
import ThreeRenderView from '@component/components/ThreeRenderView';
import { Canvas } from '@react-three/fiber';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas
        camera={{
          fov: 64,
          position: [2.3, 1.5, 2.3],
        }}
      >
        <ThreeRenderView />
      </Canvas>
    </>
  );
}
